### ISSUE TITLE
Plot features with bbox for clarity

### ISSUE THREAD

**Issue by robitalec** [marcosci/layer#4]
Neat package! 

This is the classic "What is GIS?" stacked map figure, so it's great to see a packaged solution. 
In the past, I have sheared grids and polygons to achieve a similar result. 

In some of your examples, I find the rasters really clear, but features (like the wildfire below) hard to compare to other layers. 

![image](https://user-images.githubusercontent.com/16324625/148471869-4dcd8e30-88ea-4e05-9002-5841ddbb2c3a.png)

This is similar to #1, but I was thinking instead of lines connecting down, it might help to show the shared boundaries?

Eg. taking the example in the README (I couldn't find the data for the wildfire example)

```r
library(layer)

tilt_landscape_1 <- tilt_map(landscape_1)
tilt_landscape_2 <- tilt_map(landscape_2, x_shift = 25, y_shift = 50)
tilt_landscape_3 <- tilt_map(landscape_3, x_shift = 50, y_shift = 100)
tilt_landscape_points <- tilt_map(landscape_points, x_shift = 75, y_shift = 150)

map_list <- list(tilt_landscape_1, tilt_landscape_2, tilt_landscape_3, tilt_landscape_points)

plot_tiltedmaps(map_list, 
                layer = c("value", "value", "value", NA),
                palette = c("bilbao", "mako", "rocket", NA),
                color = "grey40")
```

![image](https://user-images.githubusercontent.com/16324625/148472092-d5395e1f-a454-4558-9c36-5000101bff40.png)

Here's a rough DIY solution, where I just bind the bbox (cast as a linestring to avoid it being filled, harder to tweak a polygon I think since the ggplot'ing happens within the function). 

```r
library(layer)
library(sf)
tilt_landscape_1 <- tilt_map(landscape_1)
tilt_landscape_2 <- tilt_map(landscape_2, x_shift = 25, y_shift = 50)
tilt_landscape_3 <- tilt_map(landscape_3, x_shift = 50, y_shift = 100)
landscape_with_bbox <- rbind(
  landscape_points,
  st_cast(st_as_sfc(st_bbox(landscape_points)), 'LINESTRING')
)

tilt_landscape_with_bbox <- tilt_map(landscape_with_bbox, x_shift = 75, y_shift = 150)

map_list_with_bbox <- list(tilt_landscape_1, tilt_landscape_2, tilt_landscape_3, tilt_landscape_with_bbox)

plot_tiltedmaps(map_list_with_bbox, 
                layer = c("value", "value", "value", NA),
                palette = c("bilbao", "mako", "rocket", NA),
                color = c("grey40", "grey40", "grey40", "black"))

```
![image](https://user-images.githubusercontent.com/16324625/148472269-fc0c749e-7d2f-47bc-8dfb-c37f0d1d2f2e.png)

Maybe a broader solution for the package would be adding a toggle to `plot_tiltedmaps()` to add a boundary to all the layers?
Thank you!

**Comment by marcosci** [comment]
I see ... actually a really neat idea! I do like that a lot :)

I think we could to a `st_union` and check if the layer is coming from a raster source or different and then add the union to geometry to achieve something like you are proposing (if this makes any sense withoud code now).

**Comment by marcosci** [comment]
So, like this:

`> plot(st_union(tilt_landscape_1))`

![image](https://user-images.githubusercontent.com/10864574/148680581-3e183121-0d4c-4f34-89d6-80699f22c370.png)

Or were you aiming for the rectangular bounding box?

**Comment by robitalec** [comment]
I don't think strictly rectangular is necessary - I just didn't find the US layer in the example data, so couldn't use that in my example. 

That one looks great. I think it would really help comparing between layers that include features.

**Comment by z3tt** [comment]
Thanks @robitalec, we started with rasters only as this is the "traditional" usage but thought adding functionality for vector data would be great as well. Like you, we weren't happy that points easily get lost and I really like the outline idea as an additional option. 

I think the best would be to create the outline according to the other layers (e.g. a rectangle in our made-up example and a country shape in our wildfire example).

**Comment by marcosci** [comment]
Implemented, works like this now:

```
tilt_landscape_1 <- tilt_map(landscape_1)
tilt_landscape_2 <- tilt_map(landscape_2, x_shift = 50, y_shift = 50)
tilt_landscape_3 <- tilt_map(landscape_points, x_shift = 75, y_shift = 75, boundary = landscape_1)
map_list <- list(tilt_landscape_1, tilt_landscape_2, tilt_landscape_3)
plot_tiltedmaps(map_list, layer = c("value", "value", NA), palette = "turbo")
```

![image](https://user-images.githubusercontent.com/10864574/148823055-3e1b29a0-0924-4724-8ef2-84f1ebd0a183.png)

Any better ideas? Somehow doing that in the plot function didn't make sense in my head, but could be a current brain freeze 😆 Open to suggestions!

**Comment by z3tt** [comment]
Is this functionality available for rasters as well or constrained to vectors for now? It seems it is available for all which would be great: Here it would be helpful to have outlines for the middle raster layer as well for example.

**Comment by marcosci** [comment]
Needed some tweaking, but is reasonable fast now and works also for largish data:

![image](https://user-images.githubusercontent.com/10864574/148846268-8783182d-d8d2-4236-9ec5-74160d3f0c0f.png)

and yes, supports raster and vector 👍

**Comment by robitalec** [comment]
Awesome, that's great! 
Thanks @marcosci and @z3tt.

**Comment by marcosci** [comment]
At your service!
