### ISSUE TITLE
Error in `[[<-.data.frame`(`*tmp*`, i, value = numeric(0))

### ISSUE THREAD

**Issue by rafapereirabr** [marcosci/layer#6]
Hi all. Thanks for such a handy package!

I'm trying to use it with data from the `geobr` package, but I'm getting the following error:

```{R}

library(layer)
library(sf)
library(ggplot2)
library(geobr)

landscape_1 <- geobr::read_state()

tilt_landscape_1 <- tilt_map(landscape_1)

````

> Error in `[[<-.data.frame`(`*tmp*`, i, value = numeric(0)) : 
>   replacement has 0 rows, data has 27

It works fine with a simple ggplot `ggplot() + geom_sf(data=landscape_1, color='gray') + theme_void()`
![Rplot01](https://user-images.githubusercontent.com/7448421/148950762-f87ab7fa-7f37-49b7-85d8-580066ed6768.png)

**Comment by marcosci** [comment]
Hi Rafa!

Hm, can you try it again with the current GitHub Version?

I just tried it out and could not reproduce your error:

```
library(layer)
library(sf)
library(ggplot2)
library(geobr)

landscape_1 <- geobr::read_state()
tilt_landscape_1 <- tilt_map(landscape_1)

plot_tiltedmaps(list(tilt_landscape_1))
```

![image](https://user-images.githubusercontent.com/10864574/148956129-852c1ac3-264f-465f-858b-934a5f9b5bb8.png)

**Comment by rafapereirabr** [comment]
Thanks, Marco ! I just tried it with the dev version and it worked perfectly ! Thanks ! Please feel free to close this issue.

**Comment by marcosci** [comment]
:) Happy that it works on your end now! Let us know if something else troubles you.
